[program:phoneix]
command=/var/www/phoneix/api/start_uvicorn.sh
directory=/var/www/phoneix/api
autostart=true
autorestart=true
startretries=5
stopwaitsecs=10
stdout_logfile=/var/www/phoneix/api/logs/uvicorn.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/www/phoneix/api/logs/uvicorn.err.log
stderr_logfile_maxbytes=5MB
