[program:webdav]
command=rclone serve webdav /var/www/phoneix/files --addr 0.0.0.0:8091 --user shubhan --pass Pixel@cloud1 --vfs-cache-mode off --no-checksum
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/var/log/webdav.log
stderr_logfile=/var/log/webdav.log
